import type { NextPage } from "next";
import Head from "next/head";
import CustomConnectButton from "../components/CustomConnectButton";
import Header from "../components/Header";
import { SendTransaction } from "../components/SendTransaction";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center">
      <Head>
        <title>Cube Dapp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="min-h-scree flex bg-zinc-900">
        <div className="flex flex-col items-center justify-center p-4">
          <Header />
          <SendTransaction />
        </div>
      </main>
    </div>
  );
};

export default Home;
