import {
  ConnectButton,
  RainbowKitProvider,
  lightTheme,
} from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { SendTransaction } from "../components/SendTransaction";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center p-4">
      <Head>
        <title>Cube Dapp</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center">
        <h1 className="mb-4 text-5xl">Cube Dapp</h1>
        <RainbowKitProvider
          showRecentTransactions={true}
          appInfo={{
            appName: "Cube Dapp",
          }}
          modalSize="wide"
          theme={lightTheme()}
          locale="en"
        >
          <div className="flex flex-col items-center justify-center">
            <ConnectButton
              label="Sing in"
              chainStatus="full"
              showBalance={true}
            />
            <SendTransaction />
          </div>
        </RainbowKitProvider>
      </main>
    </div>
  );
};

export default Home;
